import XCTest
@testable import FlipperCore

final class ClassicOfflineTests: XCTestCase {
    // Independent known-answer vector: RfidResearchGroup/proxmark3 tools/pm3_tests.sh,
    // mfkey32v2 regression. Expected key A0A1A2A3A4A5; not generated by this implementation.
    static let vector = "Sec 0 key A cuid 12345678 nt0 1AD8DF2B nr0 1D316024 ar0 620EF048 nt1 30D6CB07 nr1 C52077E2 ar1 837AC61A"

    func testUpstreamKnownAnswer() throws {
        let sample = try XCTUnwrap(ClassicSample.parse(Self.vector).first)
        XCTAssertTrue(sample.matches(key: 0xA0A1A2A3A4A5))
        XCTAssertFalse(sample.matches(key: 0xFFFFFFFFFFFF))
        XCTAssertFalse(sample.matches(key: 0xA0A1A2A3A4A4))
        XCTAssertFalse(sample.matches(key: 1 << 48))
    }

    func testRequiresBothAuthentications() throws {
        for value in ["620EF048", "837AC61A", "1D316024", "C52077E2", "12345678"] {
            let changed = Self.vector.replacingOccurrences(of: value, with: "00000000")
            XCTAssertFalse(try ClassicSample.parse(changed)[0].matches(key: 0xA0A1A2A3A4A5), value)
        }
    }

    func testParserWhitespaceDedupAndKeyB() throws {
        let text = "\u{FEFF}# sample\r\n\r\n" + Self.vector + "\r" + Self.vector + "\n"
        XCTAssertEqual(try ClassicSample.parse(text).count, 1)
        let b = Self.vector.replacingOccurrences(of: "Sec 0 key A", with: "Sec 39 key B")
        XCTAssertEqual(try ClassicSample.parse(b)[0].sector, 39)
        XCTAssertEqual(try ClassicSample.parse(b)[0].keyType, "B")
        XCTAssertEqual(try ClassicSample.parse(Self.vector.replacingOccurrences(of: " ", with: "\t")).count, 1)
    }

    func testMalformedInputAndLimits() {
        let invalid = ["", "# only", "Filetype: Flipper NFC device",
            Self.vector + " trailing", Self.vector.replacingOccurrences(of: "Sec 0", with: "Sec -1"),
            Self.vector.replacingOccurrences(of: "Sec 0", with: "Sec 40"),
            Self.vector.replacingOccurrences(of: "key A", with: "key C"),
            Self.vector.replacingOccurrences(of: "12345678", with: "1234567"),
            Self.vector.replacingOccurrences(of: "12345678", with: "+2345678"),
            Self.vector.replacingOccurrences(of: "nt1 30D6CB07 nr1 C52077E2", with: "nt1 1AD8DF2B nr1 1D316024"),
            "#" + String(repeating: "x", count: NFCKeyDictionary.maxBytes)]
        for text in invalid { XCTAssertThrowsError(try ClassicSample.parse(text)) }
        let excessive = (0...ClassicSample.maxSamples).map { i in
            Self.vector.replacingOccurrences(of: "12345678", with: String(format: "%08X", i))
        }.joined(separator: "\n")
        XCTAssertThrowsError(try ClassicSample.parse(excessive))
        XCTAssertThrowsError(try ClassicSample.parse("# first\ninvalid")) {
            XCTAssertTrue($0.localizedDescription.contains("第 2 行"))
        }
    }

    func testDictionarySearchAndNoMatch() async throws {
        let samples = try ClassicSample.parse(Self.vector)
        let dictionary = try NFCKeyDictionary(text: "FFFFFFFFFFFF\nA0A1A2A3A4A5\n000000000000")
        let results = try await ClassicOffline.verify(samples: samples, dictionary: dictionary)
        XCTAssertEqual(results.first?.key, "A0A1A2A3A4A5")
        let absent = try await ClassicOffline.verify(samples: samples,
            dictionary: NFCKeyDictionary(text: "FFFFFFFFFFFF"))
        XCTAssertNil(absent.first?.key)
    }

    func testRecoveryWithoutDictionaryAndIndependentVerification() async throws {
        let samples = try ClassicSample.parse(Self.vector)
        let recovered = try await ClassicOffline.recover(samples: samples)
        XCTAssertEqual(recovered.first?.key, "A0A1A2A3A4A5")
        let malformed = Self.vector.replacingOccurrences(of: "837AC61A", with: "837AC61B")
        let absent = try await ClassicOffline.recover(samples: ClassicSample.parse(malformed))
        XCTAssertNil(absent.first?.key)
    }

    func testRecoveryCancellation() async throws {
        let samples = try ClassicSample.parse(Self.vector)
        let task = Task {
            withUnsafeCurrentTask { $0?.cancel() }
            return try await ClassicOffline.recover(samples: samples)
        }
        do { _ = try await task.value; XCTFail("Expected cancellation") }
        catch is CancellationError { }
        catch { XCTFail("Unexpected error: \(error)") }
    }

    func testCancellation() async throws {
        let samples = try ClassicSample.parse(Self.vector)
        let dictionary = try NFCKeyDictionary(text: "FFFFFFFFFFFF")
        let task = Task {
            withUnsafeCurrentTask { $0?.cancel() }
            return try await ClassicOffline.verify(samples: samples, dictionary: dictionary)
        }
        do { _ = try await task.value; XCTFail("Expected cancellation") }
        catch is CancellationError { }
        catch { XCTFail("Unexpected error: \(error)") }
    }
}
