// Generated by scripts/generate_rpc_vectors.py with the pinned Flipper schema.
// Expected bytes come from protoc + Google's Python runtime, not our Swift encoder.
import XCTest
@testable import FlipperCore

final class ProtocolVectorTests: XCTestCase {
    func testVersion() throws {
        let bytes = Data([7, 8, 3, 194, 2, 2, 16, 25])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.tag, 40)
            XCTAssertEqual(try PBMessage(frame.payload).uint(2), 25)
        }
    }
    func testDirectory() throws {
        let bytes = Data([40, 8, 255, 255, 255, 255, 15, 24, 1, 66, 30, 10, 12, 8, 1, 18, 8, 105, 110, 102, 114, 97, 114, 101, 100, 10, 14, 18, 9, 114, 101, 109, 111, 116, 101, 46, 105, 114, 24, 128, 4])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.commandID, UInt32.max)
            XCTAssertTrue(frame.hasNext)
            XCTAssertEqual(frame.tag, 8)
            let files = try PBMessage(frame.payload).blobs(1).map { try DeviceFile(parent: "/ext", message: PBMessage($0)) }
            XCTAssertEqual(files.map(\.name), ["infrared", "remote.ir"])
            XCTAssertTrue(files[0].isDirectory)
            XCTAssertFalse(files[1].isDirectory)
            XCTAssertEqual(files[1].size, 512)
        }
    }
    func testExistingDirectory() throws {
        let bytes = Data([6, 8, 9, 16, 6, 34, 0])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.status, 6)
            XCTAssertEqual(frame.tag, 4)
            XCTAssertTrue(frame.payload.isEmpty)
        }
    }
    func testReadBinary() throws {
        let bytes = Data([12, 8, 10, 82, 8, 10, 6, 34, 4, 0, 10, 128, 255])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.tag, 10)
            let file = try XCTUnwrap(PBMessage(frame.payload).bytes(1))
            XCTAssertEqual(try PBMessage(file).bytes(4), Data([0, 10, 128, 255]))
        }
    }
    func testUnsolicitedApplicationState() throws {
        let bytes = Data([5, 210, 3, 2, 8, 1])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.commandID, 0)
            XCTAssertEqual(frame.tag, 58)
            XCTAssertEqual(try PBMessage(frame.payload).uint(1), 1)
        }
    }
    func testFirstInfraredButtonUsesProtoDefaultIndex() throws {
        let bytes = Data([5, 8, 11, 218, 4, 0])
        // Test every possible transport boundary, including a split length prefix.
        for split in 0...bytes.count {
            var decoder = RPCFrameDecoder()
            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))
            XCTAssertEqual(frames.count, 1)
            let frame = try XCTUnwrap(frames.first)
            XCTAssertEqual(frame.tag, 75)
            XCTAssertEqual(try PBMessage(frame.payload).uint(2), 0)
        }
    }
}
