#include "canvas_i.h"
#include "canvas.h"
#include "icon_animation_i.h"
#include "utf8_internal.h"
// Generated by scripts/generate_native_zh_font.py: the CJK glyphs of the translated
// UI, drawn when the selected font has none. Included here only; other files get
// its metrics from utf8_internal.h instead of a second copy of the array.
#ifndef FURI_RAM_EXEC
#include "native_zh_font.h"
#else
// The recovery updater is English and must stay below the legacy 128 KiB limit.
// Do not carry the native application's CJK subset into its RAM image.
#define native_zh_font u8g2_font_haxrcorp4089_tr
#endif

#include <furi.h>
#include <furi_hal.h>
#include <stdint.h>
#include <u8g2_glue.h>
#include <momentum/asset_packs_i.h>
#include <momentum/settings.h>

const CanvasFontParameters canvas_font_params[FontTotalNumber] = {
    [FontPrimary] = {.leading_default = 12, .leading_min = 11, .height = 8, .descender = 2},
    [FontSecondary] = {.leading_default = 11, .leading_min = 9, .height = 7, .descender = 2},
    [FontKeyboard] = {.leading_default = 11, .leading_min = 9, .height = 7, .descender = 2},
    [FontBigNumbers] = {.leading_default = 18, .leading_min = 16, .height = 15, .descender = 0},
    [FontBatteryPercent] = {.leading_default = 11, .leading_min = 9, .height = 6, .descender = 0},
};

Canvas* canvas_init(void) {
    Canvas* canvas = malloc(sizeof(Canvas));
    canvas->compress_icon = compress_icon_alloc(ICON_DECOMPRESSOR_BUFFER_SIZE);

    // Initialize mutex
    canvas->mutex = furi_mutex_alloc(FuriMutexTypeNormal);

    // Initialize callback array
    CanvasCallbackPairArray_init(canvas->canvas_callback_pair);

    // Setup u8g2
    u8g2_Setup_st756x_flipper(&canvas->fb, U8G2_R0, u8x8_hw_spi_stm32, u8g2_gpio_and_delay_stm32);
    canvas->orientation = CanvasOrientationHorizontal;
    // Initialize display
    u8g2_InitDisplay(&canvas->fb);
    // Wake up display
    u8g2_SetPowerSave(&canvas->fb, 0);

    // Clear buffer and send to device
    canvas_clear(canvas);
    canvas_commit(canvas);

    return canvas;
}

void canvas_free(Canvas* canvas) {
    furi_check(canvas);
    compress_icon_free(canvas->compress_icon);
    CanvasCallbackPairArray_clear(canvas->canvas_callback_pair);
    furi_mutex_free(canvas->mutex);
    free(canvas);
}

static void canvas_lock(Canvas* canvas) {
    furi_assert(canvas);
    furi_check(furi_mutex_acquire(canvas->mutex, FuriWaitForever) == FuriStatusOk);
}

static void canvas_unlock(Canvas* canvas) {
    furi_assert(canvas);
    furi_check(furi_mutex_release(canvas->mutex) == FuriStatusOk);
}

void canvas_reset(Canvas* canvas) {
    furi_check(canvas);

    canvas_clear(canvas);

    canvas_set_color(canvas, ColorBlack);
    canvas_set_font(canvas, FontSecondary);
    canvas_set_font_direction(canvas, CanvasDirectionLeftToRight);
}

void canvas_commit(Canvas* canvas) {
    furi_check(canvas);
    u8g2_SendBuffer(&canvas->fb);

    // Iterate over callbacks
    canvas_lock(canvas);
    for
        M_EACH(p, canvas->canvas_callback_pair, CanvasCallbackPairArray_t) {
            p->callback(
                canvas_get_buffer(canvas),
                canvas_get_buffer_size(canvas),
                canvas_get_orientation(canvas),
                p->context);
        }
    canvas_unlock(canvas);
}

uint8_t* canvas_get_buffer(Canvas* canvas) {
    furi_check(canvas);
    return u8g2_GetBufferPtr(&canvas->fb);
}

size_t canvas_get_buffer_size(const Canvas* canvas) {
    furi_check(canvas);
    return u8g2_GetBufferTileWidth(&canvas->fb) * u8g2_GetBufferTileHeight(&canvas->fb) * 8;
}

void canvas_frame_set(
    Canvas* canvas,
    int32_t offset_x,
    int32_t offset_y,
    size_t width,
    size_t height) {
    furi_check(canvas);
    canvas->offset_x = offset_x;
    canvas->offset_y = offset_y;
    canvas->width = width;
    canvas->height = height;
}

size_t canvas_width(const Canvas* canvas) {
    furi_check(canvas);
    return canvas->width;
}

size_t canvas_height(const Canvas* canvas) {
    furi_check(canvas);
    return canvas->height;
}

size_t canvas_current_font_height(const Canvas* canvas) {
    furi_check(canvas);
    size_t font_height = u8g2_GetMaxCharHeight(&canvas->fb);

    if(canvas->fb.font == u8g2_font_haxrcorp4089_tr) {
        font_height += 1;
    }

    return font_height;
}

size_t canvas_current_font_width(const Canvas* canvas) {
    furi_check(canvas);
    return u8g2_GetMaxCharWidth(&canvas->fb);
}

const CanvasFontParameters* canvas_get_font_params(const Canvas* canvas, Font font) {
    furi_check(canvas);
    furi_check(font < FontTotalNumber);
    if(asset_packs && asset_packs->font_params[font]) {
        return asset_packs->font_params[font];
    }
    return &canvas_font_params[font];
}

void canvas_clear(Canvas* canvas) {
    furi_check(canvas);
    if(momentum_settings.dark_mode) {
        u8g2_FillBuffer(&canvas->fb);
    } else {
        u8g2_ClearBuffer(&canvas->fb);
    }
}

void canvas_set_color(Canvas* canvas, Color color) {
    furi_check(canvas);
    if(momentum_settings.dark_mode) {
        if(color == ColorBlack) {
            color = ColorWhite;
        } else if(color == ColorWhite) {
            color = ColorBlack;
        }
    }
    u8g2_SetDrawColor(&canvas->fb, color);
}

void canvas_set_font_direction(Canvas* canvas, CanvasDirection dir) {
    furi_check(canvas);
    u8g2_SetFontDirection(&canvas->fb, dir);
}

void canvas_invert_color(Canvas* canvas) {
    if(canvas->fb.draw_color == ColorXOR && momentum_settings.dark_mode) {
        // XOR is 0x02, invert changes it to 0x00 which is White
        // Basically like resetting to background color
        // In Dark Mode, background color is Black instead
        canvas->fb.draw_color = ColorBlack;
    } else {
        canvas->fb.draw_color = !canvas->fb.draw_color;
    }
}

void canvas_set_font(Canvas* canvas, Font font) {
    furi_check(canvas);
    u8g2_SetFontMode(&canvas->fb, 1);
    if(asset_packs && asset_packs->fonts[font]) {
        u8g2_SetFont(&canvas->fb, asset_packs->fonts[font]);
        return;
    }
    switch(font) {
    case FontPrimary:
        u8g2_SetFont(&canvas->fb, u8g2_font_helvB08_tr);
        break;
    case FontSecondary:
        u8g2_SetFont(&canvas->fb, u8g2_font_haxrcorp4089_tr);
        break;
    case FontKeyboard:
        u8g2_SetFont(&canvas->fb, u8g2_font_profont11_mr);
        break;
    case FontBigNumbers:
        u8g2_SetFont(&canvas->fb, u8g2_font_profont22_tn);
        break;
    case FontBatteryPercent:
        u8g2_SetFont(&canvas->fb, u8g2_font_5x7_tr); //u8g2_font_micro_tr);
        break;
    default:
        furi_crash();
        break;
    }
}

void canvas_set_custom_u8g2_font(Canvas* canvas, const uint8_t* font) {
    furi_check(canvas);
    u8g2_SetFontMode(&canvas->fb, 1);
    u8g2_SetFont(&canvas->fb, font);
}

// A glyph comes from the native Chinese font only when it is one of the codepoints
// that font was generated for and the selected font has no glyph for it. ASCII,
// custom fonts that carry their own CJK glyphs and the native font itself keep
// u8g2's behavior.
static bool canvas_glyph_needs_fallback(Canvas* canvas, uint16_t symbol) {
#ifdef FURI_RAM_EXEC
    (void)canvas;
    (void)symbol;
    return false;
#else
    if(!gui_utf8_is_cjk(symbol)) return false;
    if(canvas->fb.font == native_zh_font) return false;
    return !u8g2_IsGlyph(&canvas->fb, symbol);
#endif
}

// Advance of one glyph, taken from the native Chinese font when the selected font
// lacks it. The selected font is set back before returning; `fallback` is set when
// the native font was used.
static int8_t canvas_glyph_advance(Canvas* canvas, uint16_t symbol, bool* fallback) {
    if(!canvas_glyph_needs_fallback(canvas, symbol)) {
        return u8g2_GetGlyphWidth(&canvas->fb, symbol);
    }
    if(fallback) *fallback = true;
    const uint8_t* font = canvas->fb.font;
    u8g2_SetFont(&canvas->fb, native_zh_font);
    int8_t advance = u8g2_GetGlyphWidth(&canvas->fb, symbol);
    u8g2_SetFont(&canvas->fb, font);
    return advance;
}

// Draws one glyph the same way and returns its advance
static u8g2_uint_t
    canvas_glyph_draw(Canvas* canvas, u8g2_uint_t x, u8g2_uint_t y, uint16_t symbol) {
    if(!canvas_glyph_needs_fallback(canvas, symbol)) {
        return u8g2_DrawGlyph(&canvas->fb, x, y, symbol);
    }
    const uint8_t* font = canvas->fb.font;
    u8g2_SetFont(&canvas->fb, native_zh_font);
    u8g2_uint_t advance = u8g2_DrawGlyph(&canvas->fb, x, y, symbol);
    u8g2_SetFont(&canvas->fb, font);
    return advance;
}

// Width of a string that may need the native Chinese font, computed like
// u8g2_string_width(): the advances of all glyphs, the last one counted by its
// drawn width. Like u8g2, measuring stops at a newline. `fallback` is set when a
// glyph came from the native font.
static uint16_t canvas_utf8_width(Canvas* canvas, const char* str, bool* fallback) {
    u8g2_t* fb = &canvas->fb;
    int32_t width = 0;
    int8_t advance = 0;
    uint32_t codepoint;
    size_t size;

    fb->font_decode.glyph_width = 0;
    while((size = gui_utf8_decode(str, &codepoint)) > 0 && codepoint != '\n') {
        str += size;
        // u8g2 keeps the low 16 bits of non-BMP codepoints, measure what it draws
        advance = canvas_glyph_advance(canvas, (uint16_t)codepoint, fallback);
        width += advance;
    }
    if(fb->font_decode.glyph_width != 0) {
        width -= advance;
        width += fb->font_decode.glyph_width;
        width += fb->glyph_x_offset;
    }
    return (uint16_t)width;
}

// Draws a string glyph by glyph so CJK glyphs can come from the native Chinese font,
// moving along the font direction like u8g2_DrawUTF8() and stopping at a newline
static void canvas_utf8_draw(Canvas* canvas, int32_t x, int32_t y, const char* str) {
    uint32_t codepoint;
    size_t size;
    while((size = gui_utf8_decode(str, &codepoint)) > 0 && codepoint != '\n') {
        str += size;
        u8g2_uint_t advance = canvas_glyph_draw(canvas, x, y, (uint16_t)codepoint);
        switch(canvas->fb.font_decode.dir) {
        case 1:
            y += advance;
            break;
        case 2:
            x -= advance;
            break;
        case 3:
            y -= advance;
            break;
        default:
            x += advance;
            break;
        }
    }
}

void canvas_draw_str(Canvas* canvas, int32_t x, int32_t y, const char* str) {
    furi_check(canvas);
    if(!str) return;
    x += canvas->offset_x;
    y += canvas->offset_y;
    if(gui_utf8_is_ascii(str)) {
        u8g2_DrawUTF8(&canvas->fb, x, y, str);
    } else {
        canvas_utf8_draw(canvas, x, y, str);
    }
}

void canvas_draw_str_aligned(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    Align horizontal,
    Align vertical,
    const char* str) {
    furi_check(canvas);
    if(!str) return;
    x += canvas->offset_x;
    y += canvas->offset_y;

    bool ascii = gui_utf8_is_ascii(str);
    bool fallback = false;
    uint16_t width = 0;
    if(!ascii) {
        width = canvas_utf8_width(canvas, str, &fallback);
    } else if(horizontal != AlignLeft) {
        width = u8g2_GetUTF8Width(&canvas->fb, str);
    }
    // Glyphs of the native Chinese font stand taller than the ASCII fonts
    int32_t ascent = u8g2_GetAscent(&canvas->fb);
    if(fallback && ascent < GUI_CJK_GLYPH_ASCENT) {
        ascent = GUI_CJK_GLYPH_ASCENT;
    }

    switch(horizontal) {
    case AlignLeft:
        break;
    case AlignRight:
        x -= width;
        break;
    case AlignCenter:
        x -= (width / 2);
        break;
    default:
        furi_crash();
        break;
    }

    switch(vertical) {
    case AlignTop:
        y += ascent;
        break;
    case AlignBottom:
        break;
    case AlignCenter:
        y += (ascent / 2);
        break;
    default:
        furi_crash();
        break;
    }

    if(ascii) {
        u8g2_DrawUTF8(&canvas->fb, x, y, str);
    } else {
        canvas_utf8_draw(canvas, x, y, str);
    }
}

uint16_t canvas_string_width(Canvas* canvas, const char* str) {
    furi_check(canvas);
    if(!str) return 0;
    if(gui_utf8_is_ascii(str)) {
        return u8g2_GetUTF8Width(&canvas->fb, str);
    }
    return canvas_utf8_width(canvas, str, NULL);
}

size_t canvas_glyph_width(Canvas* canvas, uint16_t symbol) {
    furi_check(canvas);
    return canvas_glyph_advance(canvas, symbol, NULL);
}

void canvas_draw_bitmap(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    const uint8_t* compressed_bitmap_data) {
    furi_check(canvas);

    x += canvas->offset_x;
    y += canvas->offset_y;
    uint8_t* bitmap_data = NULL;
    compress_icon_decode(canvas->compress_icon, compressed_bitmap_data, &bitmap_data);
    canvas_draw_u8g2_bitmap(&canvas->fb, x, y, width, height, bitmap_data, IconRotation0);
}

static void _canvas_draw_icon_animation(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    int32_t width_scale,
    int32_t height_scale,
    IconAnimation* icon_animation) {
    furi_check(canvas);
    furi_check(icon_animation);
    // Ensure scale % is > 0
    furi_assert(width_scale > 0 && height_scale > 0);
    // Ensure scale % is <= 100: animated icons > 100% are buggy
    // TODO: Future, allow scaling > 100
    furi_assert(width_scale <= 100 && height_scale <= 100);

    x += canvas->offset_x;
    y += canvas->offset_y;

    uint8_t* icon_data = NULL;
    compress_icon_decode(
        canvas->compress_icon, icon_animation_get_data(icon_animation), &icon_data);

    int32_t width = icon_animation_get_width(icon_animation);
    int32_t height = icon_animation_get_height(icon_animation);
    int32_t width_scaled = (width * width_scale) / 100;
    int32_t height_scaled = (height * height_scale) / 100;

    canvas_draw_u8g2_bitmap(
        &canvas->fb, x, y, width_scaled, height_scaled, icon_data, IconRotation0);
}

void canvas_draw_icon_animation(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    IconAnimation* icon_animation) {
    _canvas_draw_icon_animation(canvas, x, y, 100, 100, icon_animation);
}

void canvas_draw_icon_animation_ex(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    int32_t width_scale,
    int32_t height_scale,
    IconAnimation* icon_animation) {
    _canvas_draw_icon_animation(canvas, x, y, width_scale, height_scale, icon_animation);
}

static void canvas_draw_u8g2_bitmap_int(
    u8g2_t* u8g2,
    u8g2_uint_t x,
    u8g2_uint_t y,
    u8g2_uint_t w,
    u8g2_uint_t h,
    bool mirror,
    bool rotation,
    const uint8_t* bitmap) {
    u8g2_uint_t blen;
    blen = w;
    blen += 7;
    blen >>= 3;

    if(rotation && !mirror) {
        x += w + 1;
    } else if(mirror && !rotation) {
        y += h - 1;
    }

    while(h > 0) {
        const uint8_t* b = bitmap;
        uint16_t len = w;
        uint16_t x0 = x;
        uint16_t y0 = y;
        uint8_t mask;
        uint8_t color = u8g2->draw_color;
        uint8_t ncolor = (color == 0 ? 1 : 0);
        mask = 1;

        while(len > 0) {
            if(u8x8_pgm_read(b) & mask) {
                u8g2->draw_color = color;
                u8g2_DrawHVLine(u8g2, x0, y0, 1, 0);
            } else if(u8g2->bitmap_transparency == 0) {
                u8g2->draw_color = ncolor;
                u8g2_DrawHVLine(u8g2, x0, y0, 1, 0);
            }

            if(rotation) {
                y0++;
            } else {
                x0++;
            }

            mask <<= 1;
            if(mask == 0) {
                mask = 1;
                b++;
            }
            len--;
        }

        u8g2->draw_color = color;
        bitmap += blen;

        if(mirror) {
            if(rotation) {
                x++;
            } else {
                y--;
            }
        } else {
            if(rotation) {
                x--;
            } else {
                y++;
            }
        }
        h--;
    }
}

void canvas_draw_u8g2_bitmap(
    u8g2_t* u8g2,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    const uint8_t* bitmap,
    IconRotation rotation) {
#ifdef U8G2_WITH_INTERSECTION
    if(u8g2_IsIntersection(u8g2, x, y, x + width, y + height) == 0) return;
#endif /* U8G2_WITH_INTERSECTION */

    switch(rotation) {
    case IconRotation0:
        canvas_draw_u8g2_bitmap_int(u8g2, x, y, width, height, 0, 0, bitmap);
        break;
    case IconRotation90:
        canvas_draw_u8g2_bitmap_int(u8g2, x, y, width, height, 0, 1, bitmap);
        break;
    case IconRotation180:
        canvas_draw_u8g2_bitmap_int(u8g2, x, y, width, height, 1, 0, bitmap);
        break;
    case IconRotation270:
        canvas_draw_u8g2_bitmap_int(u8g2, x, y, width, height, 1, 1, bitmap);
        break;
    default:
        break;
    }
}

void canvas_draw_icon_ex(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    const Icon* icon,
    IconRotation rotation) {
    furi_check(canvas);
    furi_check(icon);

    x += canvas->offset_x;
    y += canvas->offset_y;
    uint8_t* icon_data = NULL;
    icon = asset_packs_swap_icon(icon);
    compress_icon_decode(canvas->compress_icon, icon_get_frame_data(icon, 0), &icon_data);
    canvas_draw_u8g2_bitmap(
        &canvas->fb, x, y, icon_get_width(icon), icon_get_height(icon), icon_data, rotation);
}

void canvas_draw_icon(Canvas* canvas, int32_t x, int32_t y, const Icon* icon) {
    furi_check(canvas);
    furi_check(icon);

    x += canvas->offset_x;
    y += canvas->offset_y;
    uint8_t* icon_data = NULL;
    icon = asset_packs_swap_icon(icon);
    compress_icon_decode(canvas->compress_icon, icon_get_frame_data(icon, 0), &icon_data);
    canvas_draw_u8g2_bitmap(
        &canvas->fb, x, y, icon_get_width(icon), icon_get_height(icon), icon_data, IconRotation0);
}

void canvas_draw_dot(Canvas* canvas, int32_t x, int32_t y) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawPixel(&canvas->fb, x, y);
}

void canvas_draw_overlay(Canvas* canvas) {
    furi_check(canvas);
    uint8_t original = canvas->fb.draw_color;
    canvas_set_color(canvas, ColorWhite);
    for(size_t j = 0; j < canvas->height; j++) {
        bool draw_pixel = (j % 2) == 0;
        for(size_t i = 0; i < canvas->width; i += 2) {
            size_t x = i + (draw_pixel ? 0 : 1);
            if(x < canvas->width) {
                canvas_draw_dot(canvas, x, j);
            }
        }
    }
    canvas->fb.draw_color = original;
}

void canvas_draw_box(Canvas* canvas, int32_t x, int32_t y, size_t width, size_t height) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawBox(&canvas->fb, x, y, width, height);
}

void canvas_draw_rbox(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    size_t radius) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawRBox(&canvas->fb, x, y, width, height, radius);
}

void canvas_draw_frame(Canvas* canvas, int32_t x, int32_t y, size_t width, size_t height) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawFrame(&canvas->fb, x, y, width, height);
}

void canvas_draw_rframe(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    size_t radius) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawRFrame(&canvas->fb, x, y, width, height, radius);
}

void canvas_draw_line(Canvas* canvas, int32_t x1, int32_t y1, int32_t x2, int32_t y2) {
    furi_check(canvas);
    x1 += canvas->offset_x;
    y1 += canvas->offset_y;
    x2 += canvas->offset_x;
    y2 += canvas->offset_y;
    u8g2_DrawLine(&canvas->fb, x1, y1, x2, y2);
}

void canvas_draw_circle(Canvas* canvas, int32_t x, int32_t y, size_t radius) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawCircle(&canvas->fb, x, y, radius, U8G2_DRAW_ALL);
}

void canvas_draw_disc(Canvas* canvas, int32_t x, int32_t y, size_t radius) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    u8g2_DrawDisc(&canvas->fb, x, y, radius, U8G2_DRAW_ALL);
}

void canvas_draw_triangle(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t base,
    size_t height,
    CanvasDirection dir) {
    furi_check(canvas);
    if(dir == CanvasDirectionBottomToTop) {
        canvas_draw_line(canvas, x - base / 2, y, x + base / 2, y);
        canvas_draw_line(canvas, x - base / 2, y, x, y - height + 1);
        canvas_draw_line(canvas, x, y - height + 1, x + base / 2, y);
    } else if(dir == CanvasDirectionTopToBottom) {
        canvas_draw_line(canvas, x - base / 2, y, x + base / 2, y);
        canvas_draw_line(canvas, x - base / 2, y, x, y + height - 1);
        canvas_draw_line(canvas, x, y + height - 1, x + base / 2, y);
    } else if(dir == CanvasDirectionRightToLeft) {
        canvas_draw_line(canvas, x, y - base / 2, x, y + base / 2);
        canvas_draw_line(canvas, x, y - base / 2, x - height + 1, y);
        canvas_draw_line(canvas, x - height + 1, y, x, y + base / 2);
    } else if(dir == CanvasDirectionLeftToRight) {
        canvas_draw_line(canvas, x, y - base / 2, x, y + base / 2);
        canvas_draw_line(canvas, x, y - base / 2, x + height - 1, y);
        canvas_draw_line(canvas, x + height - 1, y, x, y + base / 2);
    }
}

void canvas_draw_xbm(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    const uint8_t* bitmap) {
    furi_check(canvas);
    canvas_draw_xbm_ex(canvas, x, y, width, height, IconRotation0, bitmap);
}

void canvas_draw_xbm_ex(
    Canvas* canvas,
    int32_t x,
    int32_t y,
    size_t width,
    size_t height,
    IconRotation rotation,
    const uint8_t* bitmap_data) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    canvas_draw_u8g2_bitmap(&canvas->fb, x, y, width, height, bitmap_data, rotation);
}

void canvas_draw_glyph(Canvas* canvas, int32_t x, int32_t y, uint16_t ch) {
    furi_check(canvas);
    x += canvas->offset_x;
    y += canvas->offset_y;
    canvas_glyph_draw(canvas, x, y, ch);
}

void canvas_set_bitmap_mode(Canvas* canvas, bool alpha) {
    u8g2_SetBitmapMode(&canvas->fb, alpha ? 1 : 0);
}

void canvas_set_orientation(Canvas* canvas, CanvasOrientation orientation) {
    furi_check(canvas);
    const u8g2_cb_t* rotate_cb = NULL;
    bool need_swap = false;
    if(canvas->orientation != orientation) {
        switch(orientation) {
        case CanvasOrientationHorizontal:
            need_swap = canvas->orientation == CanvasOrientationVertical ||
                        canvas->orientation == CanvasOrientationVerticalFlip;
            rotate_cb = U8G2_R0;
            break;
        case CanvasOrientationHorizontalFlip:
            need_swap = canvas->orientation == CanvasOrientationVertical ||
                        canvas->orientation == CanvasOrientationVerticalFlip;
            rotate_cb = U8G2_R2;
            break;
        case CanvasOrientationVertical:
            need_swap = canvas->orientation == CanvasOrientationHorizontal ||
                        canvas->orientation == CanvasOrientationHorizontalFlip;
            rotate_cb = U8G2_R3;
            break;
        case CanvasOrientationVerticalFlip:
            need_swap = canvas->orientation == CanvasOrientationHorizontal ||
                        canvas->orientation == CanvasOrientationHorizontalFlip;
            rotate_cb = U8G2_R1;
            break;
        default:
            furi_crash();
        }

        if(need_swap) FURI_SWAP(canvas->width, canvas->height);
        u8g2_SetDisplayRotation(&canvas->fb, rotate_cb);
        canvas->orientation = orientation;
    }
}

CanvasOrientation canvas_get_orientation(const Canvas* canvas) {
    return canvas->orientation;
}

void canvas_add_framebuffer_callback(Canvas* canvas, CanvasCommitCallback callback, void* context) {
    furi_check(canvas);

    const CanvasCallbackPair p = {callback, context};

    canvas_lock(canvas);
    furi_check(!CanvasCallbackPairArray_count(canvas->canvas_callback_pair, p));
    CanvasCallbackPairArray_push_back(canvas->canvas_callback_pair, p);
    canvas_unlock(canvas);
}

void canvas_remove_framebuffer_callback(
    Canvas* canvas,
    CanvasCommitCallback callback,
    void* context) {
    furi_check(canvas);

    const CanvasCallbackPair p = {callback, context};

    canvas_lock(canvas);
    furi_check(CanvasCallbackPairArray_count(canvas->canvas_callback_pair, p) == 1);
    CanvasCallbackPairArray_remove_val(canvas->canvas_callback_pair, p);
    canvas_unlock(canvas);
}
