/* Generated by scripts/generate_native_zh_font.py --updater. Do not edit.
 *
 * u8g2 font subset for RAM updater: CJK literals in updater and shared GUI/dialog sources. Taken from u8g2_font_wqy12_t_gb2312 in lib/u8g2/u8g2_fonts.c
 * (208526 bytes, sha256 b615e4df25357501a6a22e9a46d508910c0fa5d5198bb59837f3bcf3e6f01a80).
 * Upstream comment above that definition, verbatim:
 *   Fontname: -wenquanyi-wenquanyi bitmap song-medium-r-normal--12-120-75-75-P-119-ISO10646-1
 *   Copyright: (null)
 *   Glyphs: 7539/30503
 *   BBX Build Mode: 0
 *   (definition guarded by: #ifdef U8G2_USE_LARGE_FONTS)
 * Glyph payloads are copied unchanged. Only the header offsets, glyph count and
 * the single-block Unicode lookup table are rebuilt. Origin and licence notes:
 * applications/main/lab/README.md
 * Copyright (C) 2004-2010 WenQuanYi Project Board of Trustees and Qianqian Fang.
 * GPL v2 with font embedding exception; see applications/main/lab/FONT_LICENSE.md.
 *
 * Subset: 0 8-bit + 0 Unicode glyphs, 31 bytes.
 */
#pragma once

#include <stdint.h>

#define UPDATER_ZH_FONT_GLYPHS 0

static const uint8_t updater_zh_font[] = {
    0x00, 0x00, 0x03, 0x02, 0x04, 0x04, 0x05, 0x05, 0x05, 0x0d, 0x0d, 0x00, 0xfe, 0x08, 0xfe, 0x0a,
    0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x04, 0xff, 0xff, 0x00, 0x00,
};
