#!/usr/bin/env python3
"""Generate Flipper Lab's Chinese UI tables and u8g2 font subset.

Inputs:
  applications/main/lab/lab_content.json  screen text, topics and layout
  lib/u8g2/u8g2_fonts.c                   u8g2_font_wqy12_t_gb2312 (guarded there
                                          by U8G2_USE_LARGE_FONTS; never linked)

Outputs:
  applications/main/lab/lab_content.h     text tables and layout constants
  applications/main/lab/lab_font.h        lab_font[]: printable ASCII plus every
                                          character used by the content

Glyph payloads are copied byte for byte; only the u8g2 lookup data is rebuilt.
Every string is measured with the metrics u8g2 uses on the device, so text that
would leave its screen area fails generation. Standard library only.

    python scripts/generate_lab_font.py          # rewrite both headers
    python scripts/generate_lab_font.py --check  # exit 1 if either is stale
"""

import argparse
import ast
import hashlib
import json
import re
import struct
import sys
from pathlib import Path
from typing import Dict, FrozenSet, Iterable, List, NamedTuple, Optional, Set, Tuple

ROOT = Path(__file__).resolve().parents[1]
LAB_DIR = ROOT / "applications" / "main" / "lab"
DEFAULT_SOURCE = ROOT / "lib" / "u8g2" / "u8g2_fonts.c"
DEFAULT_SYMBOL = "u8g2_font_wqy12_t_gb2312"
DEFAULT_CONTENT = LAB_DIR / "lab_content.json"
DEFAULT_FONT_OUT = LAB_DIR / "lab_font.h"
DEFAULT_CONTENT_OUT = LAB_DIR / "lab_content.h"
DEFAULT_APPS_ROOT = ROOT / "applications"

HEADER_SIZE = 23  # U8G2_FONT_DATA_STRUCT_SIZE, lib/u8g2/u8g2_font.c
SCREEN_W = 128
SCREEN_H = 64
PRINTABLE_ASCII = range(0x20, 0x7F)
# loader_find_external_application_by_name() resolves the names of these types
LAUNCH_APP_TYPES = ("MENUEXTERNAL", "SETTINGS")
GENERATED_NOTE = "Generated by scripts/generate_lab_font.py. Do not edit."


class GeneratorError(Exception):
    """Any failure that must stop generation."""


class FontError(GeneratorError):
    """Malformed, truncated or incomplete font data."""


class ContentError(GeneratorError):
    """Invalid lab_content.json."""


def describe(code: int) -> str:
    char = chr(code)
    return f"U+{code:04X} {char!r}" if char.isprintable() else f"U+{code:04X}"


def be16(data: bytes, offset: int) -> int:
    return (data[offset] << 8) | data[offset + 1]


# ---------------------------------------------------------------------------
# C source extraction


_SIMPLE_ESCAPES = {
    "n": 10, "t": 9, "r": 13, "a": 7, "b": 8, "f": 12, "v": 11,
    "\\": 92, "'": 39, '"': 34, "?": 63,
}  # fmt: skip
_OCTAL_DIGITS = "01234567"
_HEX_DIGITS = "0123456789abcdefABCDEF"


def decode_c_string(body: str) -> bytes:
    """Decode the text between the quotes of one C string literal."""
    out = bytearray()
    i = 0
    while i < len(body):
        char = body[i]
        if char != "\\":
            if not " " <= char <= "~" or char == '"':
                raise FontError(f"unexpected character {char!r} in string literal")
            out.append(ord(char))
            i += 1
            continue
        i += 1
        if i == len(body):
            raise FontError("string literal ends with a backslash")
        char = body[i]
        if char in _OCTAL_DIGITS:  # at most three octal digits, as in C
            end = i
            while end < len(body) and end - i < 3 and body[end] in _OCTAL_DIGITS:
                end += 1
            value = int(body[i:end], 8)
        elif char == "x":  # C hex escapes consume every following hex digit
            end = i + 1
            while end < len(body) and body[end] in _HEX_DIGITS:
                end += 1
            if end == i + 1:
                raise FontError("\\x escape without hex digits")
            value = int(body[i + 1 : end], 16)
        elif char in _SIMPLE_ESCAPES:
            value, end = _SIMPLE_ESCAPES[char], i + 1
        else:
            raise FontError(f"unsupported escape \\{char}")
        if value > 0xFF:
            raise FontError(f"escape value {value:#x} does not fit in a byte")
        out.append(value)
        i = end
    return bytes(out)


def extract_font(source: str, symbol: str) -> Tuple[bytes, List[str]]:
    """Return the bytes of `symbol` and the upstream comment lines above it."""
    pattern = re.compile(
        r"const\s+uint8_t\s+" + re.escape(symbol) + r"\s*\[\s*(\d+)\s*\]\s*"
        r'(?:U8G2_FONT_SECTION\s*\(\s*"[^"\n]*"\s*\)\s*)?='
    )
    found = list(pattern.finditer(source))
    if len(found) != 1:
        raise FontError(f"expected one definition of {symbol}, found {len(found)}")
    match = found[0]
    declared = int(match.group(1))

    data = bytearray()
    literals = 0
    pos = match.end()
    while True:
        while pos < len(source) and source[pos] in " \t\r\n":
            pos += 1
        if pos == len(source):
            raise FontError(f"{symbol}: initializer is not terminated")
        if source[pos] == ";":
            break
        if source[pos] != '"':
            raise FontError(f"{symbol}: unexpected {source[pos]!r} in initializer")
        end = pos + 1
        while end < len(source) and source[end] != '"':
            if source[end] == "\n":
                break
            end += 2 if source[end] == "\\" else 1
        if end >= len(source) or source[end] != '"':
            raise FontError(f"{symbol}: unterminated string literal")
        data += decode_c_string(source[pos + 1 : end])
        literals += 1
        pos = end + 1
    if not literals:
        raise FontError(f"{symbol}: initializer has no string literal")
    # A char array keeps the literal's terminating NUL only when it has room.
    if declared == len(data) + 1:
        data.append(0)
    elif declared != len(data):
        raise FontError(
            f"{symbol}: literal holds {len(data)} bytes, array is declared [{declared}]"
        )
    return bytes(data), _upstream_comment(source[: match.start()], symbol)


def _upstream_comment(before: str, symbol: str) -> List[str]:
    end = before.rfind("*/")
    start = before.rfind("/*", 0, end)
    if end < 0 or start < 0:
        raise FontError(f"{symbol}: no upstream comment above the definition")
    for line in before[end + 2 :].splitlines():
        if line.strip() and not line.strip().startswith("#"):
            raise FontError(f"{symbol}: upstream comment is not directly above it")
    lines = [line.strip() for line in before[start + 2 : end].splitlines()]
    lines = [line.replace("*/", "* /") for line in lines if line]
    keys = {line.partition(":")[0] for line in lines if ":" in line}
    for key in ("Fontname", "Copyright", "Glyphs"):
        if key not in keys:
            raise FontError(f"{symbol}: upstream comment has no {key} field")
    guards = [line.strip() for line in before[end + 2 :].splitlines() if line.strip()]
    return lines + [f"(definition guarded by: {' '.join(guards)})"] if guards else lines


# ---------------------------------------------------------------------------
# u8g2 font format


class GlyphParams(NamedTuple):
    bits_0: int
    bits_1: int
    width: int
    height: int
    x: int
    y: int
    advance: int


class Glyph(NamedTuple):
    width: int
    height: int
    x: int
    y: int
    advance: int
    pixels: FrozenSet[Tuple[int, int]]  # (column, row), row 0 at the glyph top
    bits: int  # payload bits read by the decoder


class Font(NamedTuple):
    header: bytes
    ascii: Dict[int, bytes]  # encoding <= 0xFF -> glyph payload
    unicode: Dict[int, bytes]  # encoding > 0xFF -> glyph payload

    @property
    def params(self) -> GlyphParams:
        return GlyphParams(*self.header[2:9])

    def payload(self, code: int) -> Optional[bytes]:
        return (self.ascii if code <= 0xFF else self.unicode).get(code)


class _Bits:
    """LSB-first bit reader matching u8g2_font_decode_get_unsigned_bits()."""

    def __init__(self, payload: bytes):
        self.payload = payload
        self.pos = 0

    def unsigned(self, count: int) -> int:
        if self.pos + count > len(self.payload) * 8:
            raise FontError("glyph bitstream runs past its record")
        value = 0
        for i in range(count):
            bit = self.pos + i
            value |= ((self.payload[bit >> 3] >> (bit & 7)) & 1) << i
        self.pos += count
        return value

    def signed(self, count: int) -> int:
        return self.unsigned(count) - (1 << (count - 1))


def decode_glyph(params: GlyphParams, payload: bytes) -> Glyph:
    """Decode one glyph exactly like u8g2_font_decode_glyph()."""
    bits = _Bits(payload)
    width, height = bits.unsigned(params.width), bits.unsigned(params.height)
    x, y, advance = (bits.signed(n) for n in (params.x, params.y, params.advance))
    pixels = set()
    if width > 0:
        col = row = 0

        def run(length: int, ink: bool):
            nonlocal col, row
            while True:  # u8g2_font_decode_len()
                remaining = width - col
                if ink:
                    pixels.update((col + i, row) for i in range(min(length, remaining)))
                if length < remaining:
                    break
                length -= remaining
                col, row = 0, row + 1
            col += length

        while True:
            zeros, ones = bits.unsigned(params.bits_0), bits.unsigned(params.bits_1)
            while True:
                run(zeros, False)
                run(ones, True)
                if not bits.unsigned(1):
                    break
            if row >= height:
                break
        if any(py >= height for _, py in pixels):
            raise FontError("glyph draws below its bounding box")
    spare = len(payload) - (bits.pos + 7) // 8
    if spare > 1:
        raise FontError(f"glyph record has {spare} unused trailing bytes")
    return Glyph(width, height, x, y, advance, frozenset(pixels), bits.pos)


def parse_font(data: bytes) -> Font:
    """Parse and validate a u8g2 font, following lib/u8g2/u8g2_font.c."""
    if len(data) < HEADER_SIZE + 8:
        raise FontError("font is shorter than its header and tables")
    header = data[:HEADER_SIZE]
    params = GlyphParams(*header[2:9])
    if not all(1 <= n <= 8 for n in params):
        raise FontError(f"unsupported glyph bit widths {tuple(params)}")
    # w, h, x, y and advance fields precede the run-length data of every glyph
    min_payload = (sum(params[2:]) + 7) // 8

    ascii_glyphs: Dict[int, bytes] = {}
    starts: List[Tuple[int, int]] = []  # (offset from byte 23, encoding)
    pos = HEADER_SIZE
    while True:
        if pos + 2 > len(data):
            raise FontError("8-bit glyph table is truncated")
        code, size = data[pos], data[pos + 1]
        if size == 0:
            break
        if size < 2 + min_payload or pos + size > len(data):
            raise FontError(f"8-bit glyph {describe(code)} has a bad length {size}")
        if starts and code <= starts[-1][1]:
            raise FontError(f"8-bit glyph {describe(code)} is duplicated or unsorted")
        starts.append((pos - HEADER_SIZE, code))
        ascii_glyphs[code] = data[pos + 2 : pos + size]
        pos += size
    terminator = pos - HEADER_SIZE
    for field, first in ((17, "A"), (19, "a")):
        start = be16(header, field)
        if start != terminator and start not in {offset for offset, _ in starts}:
            raise FontError(f"start of '{first}' glyphs is not a record boundary")
        if any(code >= ord(first) for offset, code in starts if offset < start):
            raise FontError(f"start of '{first}' glyphs skips glyphs it must find")
    table = HEADER_SIZE + be16(header, 21)
    if table != pos + 2:
        raise FontError("Unicode section does not follow the 8-bit glyphs")

    blocks: List[Tuple[int, int]] = []  # (glyph position, last encoding)
    entry = block = table
    while not blocks or blocks[-1][1] != 0xFFFF:
        if entry + 4 > len(data):
            raise FontError("Unicode lookup table is truncated")
        block += be16(data, entry)
        last = be16(data, entry + 2)
        if blocks and last <= blocks[-1][1]:
            raise FontError("Unicode lookup table is not sorted")
        blocks.append((block, last))
        entry += 4
    if blocks[0][0] != entry:
        raise FontError("first Unicode block does not follow the lookup table")

    unicode_glyphs: Dict[int, bytes] = {}
    records: Set[int] = set()
    pos, previous, index = entry, 0xFF, 0
    while True:
        if pos + 2 > len(data):
            raise FontError("Unicode glyph list has no zero sentinel")
        code = be16(data, pos)
        if code == 0:
            break
        size = data[pos + 2] if pos + 2 < len(data) else 0
        if size < 3 + min_payload or pos + size > len(data):
            raise FontError(f"Unicode glyph {describe(code)} has a bad length {size}")
        if code <= previous:
            raise FontError(f"Unicode glyph {describe(code)} is duplicated or unsorted")
        while index + 1 < len(blocks) and blocks[index + 1][0] <= pos:
            index += 1
        if code > blocks[index][1]:
            raise FontError(f"lookup table cannot reach {describe(code)}")
        records.add(pos)
        unicode_glyphs[code] = data[pos + 3 : pos + size]
        previous = code
        pos += size
    if any(start not in records and start != pos for start, _ in blocks):
        raise FontError("a Unicode lookup block does not start at a glyph record")
    if pos + 2 != len(data):
        raise FontError(f"{len(data) - pos - 2} unexpected bytes after the sentinel")
    return Font(bytes(header), ascii_glyphs, unicode_glyphs)


def u8g2_lookup(data: bytes, code: int) -> Optional[bytes]:
    """Return the payload u8g2_font_get_glyph_data() finds for `code`."""
    pos = HEADER_SIZE
    if code <= 0xFF:
        if code >= ord("a"):
            pos += be16(data, 19)
        elif code >= ord("A"):
            pos += be16(data, 17)
        while data[pos + 1] != 0:
            if data[pos] == code:
                return data[pos + 2 : pos + data[pos + 1]]
            pos += data[pos + 1]
        return None
    table = pos = pos + be16(data, 21)
    while True:  # issue 596 block search, then a linear scan
        pos += be16(data, table)
        last = be16(data, table + 2)
        table += 4
        if last >= code:
            break
    while be16(data, pos) != 0:
        if be16(data, pos) == code:
            return data[pos + 3 : pos + data[pos + 2]]
        pos += data[pos + 2]
    return None


def build_subset(font: Font, codes: Iterable[int]) -> bytes:
    """Return a u8g2 font holding exactly `codes`, payloads unchanged."""
    codes = sorted(set(codes))
    missing = [code for code in codes if font.payload(code) is None]
    if missing:
        listed = ", ".join(describe(code) for code in missing)
        raise FontError(f"source font has no glyph for {listed}")

    ascii_part = bytearray()
    upper = lower = None
    for code in (c for c in codes if c <= 0xFF):
        payload = font.ascii[code]
        if code >= ord("A") and upper is None:
            upper = len(ascii_part)
        if code >= ord("a") and lower is None:
            lower = len(ascii_part)
        ascii_part += bytes((code, 2 + len(payload))) + payload
    terminator = len(ascii_part)
    ascii_part += b"\0\0"

    unicode_part = bytearray(struct.pack(">HH", 4, 0xFFFF))  # one block
    for code in (c for c in codes if c > 0xFF):
        payload = font.unicode[code]
        unicode_part += struct.pack(">HB", code, 3 + len(payload)) + payload
    unicode_part += b"\0\0"

    header = bytearray(font.header)
    header[0] = len(codes) & 0xFF  # u8g2 stores the glyph count modulo 256
    offsets = (terminator if upper is None else upper,
               terminator if lower is None else lower,
               len(ascii_part))  # fmt: skip
    for value in offsets:
        if value > 0xFFFF:
            raise FontError(f"8-bit section offset {value} overflows 16 bits")
    header[17:23] = struct.pack(">HHH", *offsets)
    return bytes(header + ascii_part + unicode_part)


class Metrics:
    """Measure text like canvas_string_width() with a given font."""

    def __init__(self, font: Font):
        self.font = font
        self._glyphs: Dict[int, Glyph] = {}

    def glyph(self, code: int) -> Glyph:
        if code not in self._glyphs:
            payload = self.font.payload(code)
            if payload is None:
                raise FontError(f"font has no glyph for {describe(code)}")
            self._glyphs[code] = decode_glyph(self.font.params, payload)
        return self._glyphs[code]

    def width(self, text: str) -> int:
        """u8g2_GetUTF8Width(): advances, with the last glyph's real extent."""
        total = advance = last_width = last_x = 0
        for char in text:
            glyph = self.glyph(ord(char))
            advance, last_width, last_x = glyph.advance, glyph.width, glyph.x
            total += advance
        if last_width:
            total += last_width + last_x - advance
        return total

    def ink(self, text: str) -> Tuple[int, int, int, int]:
        """(left, right, above, below): pixels drawn around the pen origin."""
        pen, left, right, above, below = 0, 0, 0, 0, 0
        for char in text:
            glyph = self.glyph(ord(char))
            if glyph.width and glyph.height:
                left = min(left, pen + glyph.x)
                right = max(right, pen + glyph.x + glyph.width)
                above = max(above, glyph.height + glyph.y)
                below = max(below, -glyph.y)
            pen += glyph.advance
        return left, right, above, below


# ---------------------------------------------------------------------------
# Content


LAYOUT_KEYS = (
    "text_x", "text_max_width", "list_width", "indicator_right", "indicator_gap",
    "title_baseline", "rows_top", "row_height", "row_baseline", "rows",
    "footer_baseline", "max_wide_chars",
)  # fmt: skip
UI_KEYS = ("menu_title", "menu_footer", "detail_footer", "detail_footer_launch", "indicator")
TOPIC_KEYS = ("id", "menu", "title", "launch", "pages")


class Page(NamedTuple):
    indicator: str
    lines: Tuple[str, ...]


class Topic(NamedTuple):
    id: str
    label: str
    indicator: str
    title: str
    footer: str
    launch: Optional[str]
    pages: Tuple[Page, ...]


class Content(NamedTuple):
    layout: Dict[str, int]
    menu_title: str
    menu_footer: str
    topics: Tuple[Topic, ...]

    def strings(self) -> Iterable[str]:
        yield self.menu_title
        yield self.menu_footer
        for topic in self.topics:
            yield from (topic.label, topic.indicator, topic.title, topic.footer)
            for page in topic.pages:
                yield page.indicator
                yield from page.lines


def _object(value, where: str, keys: Tuple[str, ...], optional: Tuple[str, ...] = ()) -> dict:
    if not isinstance(value, dict):
        raise ContentError(f"{where} must be an object")
    unknown = sorted(set(value) - set(keys) - set(optional))
    missing = [key for key in keys if key not in value]
    if unknown or missing:
        raise ContentError(f"{where}: unknown keys {unknown}, missing keys {missing}")
    return value


def _text(value, where: str, max_wide: int) -> str:
    if not isinstance(value, str) or not value:
        raise ContentError(f"{where} must be a non-empty string")
    if value != value.strip():
        raise ContentError(f"{where} has leading or trailing whitespace")
    for char in value:
        code = ord(char)
        if code < 0x20 or 0x7F <= code < 0xA0 or 0xD800 <= code < 0xE000 or code > 0xFFFD:
            raise ContentError(f"{where} contains unsupported {describe(code)}")
    wide = sum(1 for char in value if ord(char) > 0x7F)
    if wide > max_wide:
        raise ContentError(f"{where}: {wide} non-ASCII characters, limit is {max_wide}")
    return value


def _indicator(template: str, index: int, count: int) -> str:
    try:
        return template.format(index=index, count=count)
    except (KeyError, IndexError, ValueError) as error:
        raise ContentError(f"ui.indicator is not a valid template: {error}") from None


def load_content(raw) -> Content:
    """Validate the JSON structure and expand indicators and footers."""
    raw = _object(raw, "content", ("schema_version", "layout", "ui", "topics"), ("notes",))
    if raw["schema_version"] != 1 or isinstance(raw["schema_version"], bool):
        raise ContentError("schema_version must be 1")
    if not isinstance(raw.get("notes", ""), str):
        raise ContentError("notes must be a string")
    layout = _object(raw["layout"], "layout", LAYOUT_KEYS)
    for key, value in layout.items():
        if not isinstance(value, int) or isinstance(value, bool) or not 0 < value <= SCREEN_W:
            raise ContentError(f"layout.{key} must be an integer in 1..{SCREEN_W}")
    wide = layout["max_wide_chars"]
    ui = _object(raw["ui"], "ui", UI_KEYS)
    text = {key: _text(ui[key], f"ui.{key}", wide) for key in UI_KEYS}

    topics_raw = raw["topics"]
    if not isinstance(topics_raw, list) or not 1 <= len(topics_raw) <= 99:
        raise ContentError("topics must be a list of 1..99 topics")
    topics, ids = [], set()
    for number, item in enumerate(topics_raw, 1):
        where = f"topics[{number - 1}]"
        item = _object(item, where, TOPIC_KEYS)
        topic_id = item["id"]
        if not isinstance(topic_id, str) or not re.fullmatch(r"[a-z][a-z0-9_]*", topic_id):
            raise ContentError(f"{where}.id must be a lowercase C identifier")
        if topic_id in ids:
            raise ContentError(f"duplicate topic id {topic_id!r}")
        ids.add(topic_id)
        launch = item["launch"]
        if launch is not None and not (isinstance(launch, str) and launch.strip()):
            raise ContentError(f"{where}.launch must be null or an app name")
        pages_raw = item["pages"]
        if not isinstance(pages_raw, list) or not 1 <= len(pages_raw) <= 99:
            raise ContentError(f"{where}.pages must be a list of 1..99 pages")
        pages = []
        for page_number, lines in enumerate(pages_raw, 1):
            page_where = f"{where}.pages[{page_number - 1}]"
            if not isinstance(lines, list) or not 1 <= len(lines) <= layout["rows"]:
                raise ContentError(f"{page_where} must hold 1..{layout['rows']} lines")
            lines = [_text(line, f"{page_where}[{i}]", wide) for i, line in enumerate(lines)]
            lines += [""] * (layout["rows"] - len(lines))
            indicator = _indicator(text["indicator"], page_number, len(pages_raw))
            pages.append(Page(_text(indicator, f"{page_where} indicator", wide), tuple(lines)))
        footer = text["detail_footer_launch" if launch else "detail_footer"]
        indicator = _indicator(text["indicator"], number, len(topics_raw))
        topics.append(
            Topic(
                topic_id,
                _text(item["menu"], f"{where}.menu", wide),
                _text(indicator, f"{where} indicator", wide),
                _text(item["title"], f"{where}.title", wide),
                footer,
                launch,
                tuple(pages),
            )
        )
    return Content(dict(layout), text["menu_title"], text["menu_footer"], tuple(topics))


def known_launch_names(apps_root: Path) -> Set[str]:
    """Names the loader resolves: MENUEXTERNAL apps and SETTINGS apps."""
    names = set()
    for group in ("main", "settings"):
        for manifest in sorted((apps_root / group).glob("*/application.fam")):
            tree = ast.parse(manifest.read_text(encoding="utf-8"), str(manifest))
            for node in ast.walk(tree):
                if not (isinstance(node, ast.Call) and getattr(node.func, "id", "") == "App"):
                    continue
                args = {kw.arg: kw.value for kw in node.keywords}
                apptype, name = args.get("apptype"), args.get("name")
                if (
                    isinstance(apptype, ast.Attribute)
                    and apptype.attr in LAUNCH_APP_TYPES
                    and isinstance(name, ast.Constant)
                    and isinstance(name.value, str)
                ):
                    names.add(name.value)
    return names


def check_launch_targets(content: Content, names: Set[str]):
    for topic in content.topics:
        if topic.launch is not None and topic.launch not in names:
            raise ContentError(
                f"topic {topic.id!r} launches {topic.launch!r}, which is not the name of "
                "a MENUEXTERNAL or SETTINGS app in applications/main or applications/settings"
            )


def screen_bands(layout: Dict[str, int]) -> Dict[str, Tuple[int, int, int]]:
    """Vertical bands as (top row, bottom row, baseline); rules sit between."""
    rule_top = layout["rows_top"] - 1
    rule_bottom = layout["rows_top"] + layout["rows"] * layout["row_height"]
    if rule_top < 1 or rule_bottom > SCREEN_H - 2:
        raise ContentError("layout rows do not leave room for the title and footer")
    if layout["row_baseline"] > layout["row_height"]:
        raise ContentError("layout.row_baseline must lie inside a row")
    return {
        "title": (0, rule_top - 1, layout["title_baseline"]),
        "row": (0, layout["row_height"] - 1, layout["row_baseline"]),  # per-row offsets
        "footer": (rule_bottom + 1, SCREEN_H - 1, layout["footer_baseline"]),
    }


def check_layout(content: Content, metrics: Metrics):
    """Every string must stay inside its horizontal limit and vertical band."""
    layout = content.layout
    bands = screen_bands(layout)
    x, max_width = layout["text_x"], layout["text_max_width"]
    if not x + max_width <= layout["list_width"] <= SCREEN_W - 4:
        raise ContentError("text must fit the list box, which must leave a scrollbar")
    if layout["indicator_right"] > SCREEN_W:
        raise ContentError("layout.indicator_right is off screen")

    def fit(text: str, band: str, limit: int, where: str):
        if not text:
            return
        width = metrics.width(text)
        left, right, above, below = metrics.ink(text)
        top, bottom, baseline = bands[band]
        if width > limit or right > limit or x + left < 0:
            raise ContentError(f"{where} {text!r} is {max(width, right)} px, limit {limit}")
        if baseline - above < top or baseline + below - 1 > bottom:
            raise ContentError(f"{where} {text!r} leaves its {band} band vertically")

    def fit_title(title: str, indicators: List[str], where: str):
        widest = max(metrics.width(indicator) for indicator in indicators)
        limit = layout["indicator_right"] - widest - layout["indicator_gap"] - x
        fit(title, "title", limit, where)
        for indicator in indicators:
            fit(indicator, "title", layout["indicator_right"], f"{where} indicator")

    fit_title(content.menu_title, [t.indicator for t in content.topics], "menu title")
    fit(content.menu_footer, "footer", max_width, "menu footer")
    for topic in content.topics:
        where = f"topic {topic.id!r}"
        fit(topic.label, "row", max_width, f"{where} menu label")
        fit(topic.footer, "footer", max_width, f"{where} footer")
        fit_title(topic.title, [page.indicator for page in topic.pages], f"{where} title")
        for number, page in enumerate(topic.pages, 1):
            for line in page.lines:
                fit(line, "row", max_width, f"{where} page {number}")


def required_codes(content: Content) -> Set[int]:
    return set(PRINTABLE_ASCII) | {ord(char) for text in content.strings() for char in text}


def verify_subset(source: Font, subset_data: bytes, codes: Set[int]) -> Font:
    """Re-parse the subset and check the device lookup finds the same glyphs."""
    subset = parse_font(subset_data)
    if set(subset.ascii) | set(subset.unicode) != codes:
        raise FontError("subset glyph set differs from the requested characters")
    for code in sorted(codes):
        if u8g2_lookup(subset_data, code) != source.payload(code):
            raise FontError(f"device lookup of {describe(code)} returns wrong data")
        decode_glyph(subset.params, subset.payload(code))
    for code in sorted({c + 1 for c in codes} - codes):
        if u8g2_lookup(subset_data, code) is not None:
            raise FontError(f"device lookup invents a glyph for {describe(code)}")
    return subset


# ---------------------------------------------------------------------------
# Output


def c_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("?", "\\?")
    return f'"{escaped}"'


def render_font_header(data: bytes, subset: Font, comment: List[str], source: str,
                       symbol: str, source_data: bytes) -> str:  # fmt: skip
    rows = [
        "    " + ", ".join(f"0x{byte:02x}" for byte in data[i : i + 12]) + ","
        for i in range(0, len(data), 12)
    ]
    upstream = "\n".join(f" *   {line}" for line in comment)
    return f"""/* {GENERATED_NOTE}
 *
 * u8g2 font subset for Flipper Lab: printable ASCII plus every character in
 * lab_content.json. Taken from {symbol} in {source}
 * ({len(source_data)} bytes, sha256 {hashlib.sha256(source_data).hexdigest()}).
 * Upstream comment above that definition, verbatim:
{upstream}
 * Glyph payloads are copied unchanged. Only the header offsets, glyph count and
 * the single-block Unicode lookup table are rebuilt. Origin and licence notes:
 * applications/main/lab/README.md
 *
 * Subset: {len(subset.ascii)} 8-bit + {len(subset.unicode)} Unicode glyphs, {len(data)} bytes.
 */
#pragma once

#include <stdint.h>

#define LAB_FONT_GLYPHS {len(subset.ascii) + len(subset.unicode)}

static const uint8_t lab_font[] = {{
{chr(10).join(rows)}
}};
"""


def render_content_header(content: Content) -> str:
    layout = content.layout
    bands = screen_bands(layout)
    max_bytes = max(len(text.encode("utf-8")) for text in content.strings())
    defines = {
        "LAB_TEXT_X": layout["text_x"],
        "LAB_TEXT_MAX_W": layout["text_max_width"],
        "LAB_LIST_W": layout["list_width"],
        "LAB_INDICATOR_RIGHT": layout["indicator_right"],
        "LAB_INDICATOR_GAP": layout["indicator_gap"],
        "LAB_TITLE_Y": bands["title"][2],
        "LAB_RULE_TOP": bands["title"][1] + 1,
        "LAB_ROWS_TOP": layout["rows_top"],
        "LAB_ROW_H": layout["row_height"],
        "LAB_ROW_BASELINE": layout["row_baseline"],
        "LAB_ROWS": layout["rows"],
        "LAB_RULE_BOTTOM": bands["footer"][0] - 1,
        "LAB_FOOTER_Y": bands["footer"][2],
        "LAB_TEXT_MAX_BYTES": max_bytes,
        "LAB_TOPIC_COUNT": len(content.topics),
    }
    out = [
        f"/* {GENERATED_NOTE}",
        " * Source: applications/main/lab/lab_content.json",
        " * Every string was measured against lab_font.h for its screen area.",
        " */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    out += [f"#define {name} {value}" for name, value in defines.items()]
    out += [
        "",
        "typedef struct {",
        "    const char* indicator;",
        "    const char* lines[LAB_ROWS];",
        "} LabPage;",
        "",
        "typedef struct {",
        "    const char* label;",
        "    const char* indicator;",
        "    const char* title;",
        "    const char* footer;",
        "    const char* launch; /* loader app name, or NULL */",
        "    const LabPage* pages;",
        "    uint8_t page_count;",
        "} LabTopic;",
        "",
        f"static const char lab_menu_title[] = {c_string(content.menu_title)};",
        f"static const char lab_menu_footer[] = {c_string(content.menu_footer)};",
    ]
    for topic in content.topics:
        out += ["", f"static const LabPage lab_pages_{topic.id}[] = {{"]
        for page in topic.pages:
            lines = ", ".join(c_string(line) for line in page.lines)
            out.append(f"    {{{c_string(page.indicator)}, {{{lines}}}}},")
        out.append("};")
    out += ["", "static const LabTopic lab_topics[LAB_TOPIC_COUNT] = {"]
    for topic in content.topics:
        launch = c_string(topic.launch) if topic.launch else "NULL"
        out += [
            "    {",
            f"        .label = {c_string(topic.label)},",
            f"        .indicator = {c_string(topic.indicator)},",
            f"        .title = {c_string(topic.title)},",
            f"        .footer = {c_string(topic.footer)},",
            f"        .launch = {launch},",
            f"        .pages = lab_pages_{topic.id},",
            f"        .page_count = {len(topic.pages)},",
            "    },",
        ]
    out += ["};", ""]
    return "\n".join(out)


def generate(source: Path, symbol: str, content_path: Path,
             launch_names: Optional[Set[str]] = None) -> Tuple[str, str]:  # fmt: skip
    """Return the text of (lab_font.h, lab_content.h)."""
    try:
        source_text = source.read_text(encoding="latin-1")
        raw = json.loads(content_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, ValueError) as error:
        raise GeneratorError(f"cannot read inputs: {error}") from None
    content = load_content(raw)
    if launch_names is not None:
        check_launch_targets(content, launch_names)
    source_data, comment = extract_font(source_text, symbol)
    font = parse_font(source_data)
    codes = required_codes(content)
    data = build_subset(font, codes)
    subset = verify_subset(font, data, codes)
    check_layout(content, Metrics(subset))
    source_name = _shown(source) if source.resolve().is_relative_to(ROOT) else source.name
    return (
        render_font_header(data, subset, comment, source_name, symbol, source_data),
        render_content_header(content),
    )


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL)
    parser.add_argument("--content", type=Path, default=DEFAULT_CONTENT)
    parser.add_argument("--font-out", type=Path, default=DEFAULT_FONT_OUT)
    parser.add_argument("--content-out", type=Path, default=DEFAULT_CONTENT_OUT)
    parser.add_argument(
        "--apps-root",
        type=Path,
        default=DEFAULT_APPS_ROOT,
        help="applications/ directory used to validate launch names",
    )
    parser.add_argument("--no-app-check", action="store_true", help="skip launch-name check")
    args = parser.parse_args(argv)

    try:
        names = None if args.no_app_check else known_launch_names(args.apps_root)
        font_h, content_h = generate(args.source, args.symbol, args.content, names)
    except (GeneratorError, OSError, SyntaxError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    stale = []
    for path, text in ((args.font_out, font_h), (args.content_out, content_h)):
        data = text.encode("utf-8")
        if path.exists() and path.read_bytes() == data:
            continue
        if args.check:
            stale.append(path)
        else:
            path.write_bytes(data)
            print(f"wrote {_shown(path)}")
    for path in stale:
        print(f"stale: {_shown(path)} (run scripts/generate_lab_font.py)", file=sys.stderr)
    return 1 if stale else 0


def _shown(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


if __name__ == "__main__":
    sys.exit(main())
