"""Regenerate Swift interoperability tests with protoc and the pinned .proto files.

Run with the firmware toolchain's Python (protobuf installed), passing --protoc
if protoc is not on PATH. This is a developer regeneration tool, not app code.
"""

import argparse
import importlib
from pathlib import Path
import subprocess
import sys
import tempfile

# Keep a Windows subst drive intact: older protoc cannot open Unicode paths.
ROOT = Path(__file__).absolute().parents[1]
OUTPUT = ROOT / "mobile/FlipperLab/Tests/FlipperCoreTests/ProtocolVectorTests.swift"


def generate(protoc):
    from google.protobuf.internal.encoder import _VarintBytes

    with tempfile.TemporaryDirectory(prefix="flipper-proto-") as folder:
        schema = ROOT / "assets/protobuf"
        subprocess.run(
            [protoc, "-I" + str(schema), "--python_out=" + folder]
            + [str(path) for path in sorted(schema.glob("*.proto"))],
            check=True,
        )
        sys.path.insert(0, folder)
        try:
            pb = importlib.import_module("flipper_pb2")
            cases = []

            def case(name, message, checks):
                payload = message.SerializeToString(deterministic=True)
                wire = _VarintBytes(len(payload)) + payload
                cases.append((name, list(wire), checks))

            message = pb.Main(command_id=3)
            message.system_protobuf_version_response.major = 0
            message.system_protobuf_version_response.minor = 25
            case("Version", message, [
                "XCTAssertEqual(frame.tag, 40)",
                "XCTAssertEqual(try PBMessage(frame.payload).uint(2), 25)",
            ])
            message = pb.Main(command_id=0xffffffff, has_next=True)
            entry = message.storage_list_response.file.add()
            entry.type = 1
            entry.name = "infrared"
            entry = message.storage_list_response.file.add()
            entry.name = "remote.ir"
            entry.size = 512
            case("Directory", message, [
                "XCTAssertEqual(frame.commandID, UInt32.max)",
                "XCTAssertTrue(frame.hasNext)",
                "XCTAssertEqual(frame.tag, 8)",
                "let files = try PBMessage(frame.payload).blobs(1).map { try DeviceFile(parent: \"/ext\", message: PBMessage($0)) }",
                "XCTAssertEqual(files.map(\\.name), [\"infrared\", \"remote.ir\"])",
                "XCTAssertTrue(files[0].isDirectory)",
                "XCTAssertFalse(files[1].isDirectory)",
                "XCTAssertEqual(files[1].size, 512)",
            ])
            message = pb.Main(command_id=9, command_status=6)
            message.empty.SetInParent()
            case("ExistingDirectory", message, [
                "XCTAssertEqual(frame.status, 6)",
                "XCTAssertEqual(frame.tag, 4)",
                "XCTAssertTrue(frame.payload.isEmpty)",
            ])
            message = pb.Main(command_id=10)
            message.storage_read_response.file.data = bytes([0, 10, 128, 255])
            case("ReadBinary", message, [
                "XCTAssertEqual(frame.tag, 10)",
                "let file = try XCTUnwrap(PBMessage(frame.payload).bytes(1))",
                "XCTAssertEqual(try PBMessage(file).bytes(4), Data([0, 10, 128, 255]))",
            ])
            message = pb.Main()
            message.app_state_response.state = 1
            case("UnsolicitedApplicationState", message, [
                "XCTAssertEqual(frame.commandID, 0)",
                "XCTAssertEqual(frame.tag, 58)",
                "XCTAssertEqual(try PBMessage(frame.payload).uint(1), 1)",
            ])
            message = pb.Main(command_id=11)
            message.app_button_press_release_request.index = 0
            case("FirstInfraredButtonUsesProtoDefaultIndex", message, [
                "XCTAssertEqual(frame.tag, 75)",
                "XCTAssertEqual(try PBMessage(frame.payload).uint(2), 0)",
            ])
        finally:
            sys.path.pop(0)
    lines = [
        "// Generated by scripts/generate_rpc_vectors.py with the pinned Flipper schema.",
        "// Expected bytes come from protoc + Google's Python runtime, not our Swift encoder.",
        "import XCTest",
        "@testable import FlipperCore",
        "",
        "final class ProtocolVectorTests: XCTestCase {",
    ]
    for name, wire, checks in cases:
        lines += [
            "    func test" + name + "() throws {",
            "        let bytes = Data(" + str(wire) + ")",
            "        // Test every possible transport boundary, including a split length prefix.",
            "        for split in 0...bytes.count {",
            "            var decoder = RPCFrameDecoder()",
            "            let frames = try decoder.append(bytes.prefix(split)) + decoder.append(bytes.dropFirst(split))",
            "            XCTAssertEqual(frames.count, 1)",
            "            let frame = try XCTUnwrap(frames.first)",
        ]
        lines += ["            " + check for check in checks]
        lines += ["        }", "    }"]
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protoc", default="protoc")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate(args.protoc)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf8") != result:
            raise SystemExit("Protocol vectors are stale; regenerate them.")
    else:
        OUTPUT.write_text(result, encoding="utf8", newline="\n")
    print("Verified 6 independent protobuf vectors.")
