#!/usr/bin/env python3
"""Pack original CJK glyph pixels into bounded, directly addressable SD records.

No image resampling: metrics and pixels come from the licensed u8g2 source font.
The renderer reconstructs one small u8g2 font in a bounded cache. The complete
Unicode table is never loaded into RAM and is not linked into the main firmware.
"""
import argparse
import hashlib
from pathlib import Path
import struct
import sys

from generate_lab_font import (
    extract_font,
    parse_font,
    decode_glyph,
    build_subset,
    render_font_header,
)
from generate_native_zh_font import required_characters, TOKEN

ROOT = Path(__file__).resolve().parents[1]
GUI = ROOT / "applications/services/gui"
RESOURCE = GUI / "resources/locale/zh_cn.glyphs"
META = GUI / "native_zh_resource_data.h"
BOOT = GUI / "native_zh_boot_font.h"
RECORD_SIZE = 32
HEADER_SIZE = 64
SLOTS = 0x7000 + 0xEF


def slot(code):
    if 0x3000 <= code <= 0x9FFF:
        return code - 0x3000
    if 0xFF01 <= code <= 0xFFEF:
        return 0x7000 + code - 0xFF01
    raise ValueError(f"Unsupported CJK codepoint: {code:#x}")


def record(code, glyph):
    if not (
        0 <= glyph.width <= 12
        and 0 <= glyph.height <= 12
        and -16 <= glyph.x <= 15
        and -16 <= glyph.y <= 15
        and 0 <= glyph.advance <= 31
    ):
        raise ValueError(f"Glyph {code:#x} exceeds the bounded format")
    result = bytearray(RECORD_SIZE)
    result[:8] = struct.pack(
        ">HBBBBBB",
        code,
        glyph.width,
        glyph.height,
        glyph.x + 128,
        glyph.y + 128,
        glyph.advance + 128,
        0,
    )
    for x, y in glyph.pixels:
        bit = y * glyph.width + x
        assert 0 <= bit < 144
        result[8 + bit // 8] |= 1 << (bit % 8)
    return bytes(result)


def generate():
    source, comment = extract_font(
        (ROOT / "lib/u8g2/u8g2_fonts.c").read_text(encoding="utf-8"),
        "u8g2_font_wqy12_t_gb2312",
    )
    font = parse_font(source)
    codes = sorted(
        c for c in font.unicode if 0x3000 <= c <= 0x9FFF or 0xFF01 <= c <= 0xFFEF
    )
    required = required_characters()
    assert required <= set(codes), "The source font lacks required UI glyphs"
    header = b"FZCJK2\0\0" + hashlib.sha256(source).digest()
    header += struct.pack("<II", RECORD_SIZE, SLOTS)
    header = header.ljust(HEADER_SIZE, b"\0")
    output = bytearray(header + bytes(SLOTS * RECORD_SIZE))
    metrics = []
    for code in codes:
        glyph = decode_glyph(font.params, font.payload(code))
        offset = HEADER_SIZE + slot(code) * RECORD_SIZE
        output[offset : offset + RECORD_SIZE] = record(code, glyph)
        # u8g2's last-character extent is width+x; all other characters advance.
        extent = glyph.width + glyph.x if glyph.width else 0
        if (glyph.advance, extent) != (12, 11):
            assert 0 <= extent <= 255
            metrics.append((code, glyph.advance, extent))
    boot_codes = required_characters(updater=True)
    labels = (ROOT / "applications/services/locale/locale_ui.h").read_text(
        encoding="utf-8"
    )
    for match in TOKEN.finditer(labels):
        boot_codes.update(ord(c) for c in (match.group(1) or "") if ord(c) in codes)
    boot_codes.update(map(ord, "中文资源未加载请检查卡后重启设备确定取消返回"))
    captions = (
        ROOT / "applications/services/desktop/animations/views/animation_caption.c"
    ).read_text(encoding="utf-8")
    for match in TOKEN.finditer(captions):
        boot_codes.update(ord(c) for c in (match.group(1) or "") if ord(c) in codes)
    boot_data = build_subset(font, boot_codes)
    boot_header = render_font_header(
        boot_data,
        parse_font(boot_data),
        comment,
        "lib/u8g2/u8g2_fonts.c",
        "u8g2_font_wqy12_t_gb2312",
        source,
    )
    boot_header = boot_header.replace(
        "scripts/generate_lab_font.py", "scripts/generate_zh_resource.py"
    )
    boot_header = boot_header.replace("lab_font[]", "native_zh_boot_font[]")
    boot_header = boot_header.replace("LAB_FONT_GLYPHS", "NATIVE_ZH_BOOT_GLYPHS")
    boot_header = boot_header.replace(
        "see FONT_LICENSE.md beside this file",
        "see applications/main/lab/FONT_LICENSE.md",
    )
    boot_header = boot_header.replace(
        "Flipper Lab: printable ASCII plus every character in\n * lab_content.json",
        "Boot CJK subset: recovery, system menu names and resource errors",
    )
    font_header = bytearray(font.header)
    font_header[0] = 1
    font_header[2:9] = bytes((4, 4, 4, 4, 5, 5, 6))
    font_header[17:23] = struct.pack(">HHH", 0, 0, 2)
    array = lambda data: ", ".join(f"0x{x:02x}" for x in data)
    meta = "/* Generated by scripts/generate_zh_resource.py; do not edit. */\n#pragma once\n#include <stdint.h>\n// clang-format off\n"
    meta += f"#define NATIVE_ZH_RESOURCE_GLYPHS {len(codes)}\n"
    meta += f"#define NATIVE_ZH_RESOURCE_SIZE {len(output)}u\n"
    meta += f"#define NATIVE_ZH_RESOURCE_HEADER {{{array(header)}}}\n"
    meta += f"#define NATIVE_ZH_SINGLE_HEADER {{{array(font_header)}}}\n"
    meta += "#ifdef NATIVE_ZH_INCLUDE_METRICS\n"
    meta += "typedef struct { uint16_t code; uint8_t advance; uint8_t extent; } NativeZhMetric;\n"
    meta += "static const NativeZhMetric native_zh_metrics[] = {\n"
    meta += "".join(f"    {{0x{c:04x}, {a}, {e}}},\n" for c, a, e in metrics)
    meta += "};\n#endif\n// clang-format on\n"
    return bytes(output), meta, boot_header


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data, meta, boot = generate()
    outputs = ((RESOURCE, data), (META, meta.encode()), (BOOT, boot.encode()))
    for path, expected in outputs:
        if args.check:
            actual = path.read_bytes() if path.exists() else None
            if actual is not None and path != RESOURCE:
                actual = actual.replace(b"\r\n", b"\n")
            if actual != expected:
                print(
                    f"Chinese resource is stale: {path.relative_to(ROOT)}",
                    file=sys.stderr,
                )
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
