/* Generated by scripts/generate_lab_font.py. Do not edit.
 * Source: applications/main/lab/lab_content.json
 * Every string was measured against lab_font.h for its screen area.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#define LAB_TEXT_X          2
#define LAB_TEXT_MAX_W      120
#define LAB_LIST_W          124
#define LAB_INDICATOR_RIGHT 126
#define LAB_INDICATOR_GAP   4
#define LAB_TITLE_Y         11
#define LAB_RULE_TOP        13
#define LAB_ROWS_TOP        14
#define LAB_ROW_H           12
#define LAB_ROW_BASELINE    10
#define LAB_ROWS            3
#define LAB_RULE_BOTTOM     50
#define LAB_FOOTER_Y        62
#define LAB_TEXT_MAX_BYTES  19
#define LAB_TOPIC_COUNT     10

typedef struct {
    const char* indicator;
    const char* lines[LAB_ROWS];
} LabPage;

typedef struct {
    const char* label;
    const char* indicator;
    const char* title;
    const char* footer;
    const char* launch; /* loader app name, or NULL */
    const LabPage* pages;
    uint8_t page_count;
} LabTopic;

static const char lab_menu_title[] = "Feature Guide";
static const char lab_menu_footer[] = "Up/Dn pick, OK open";

static const LabPage lab_pages_about[] = {
    {"1/4", {"A short guide to", "using each feature", "No signal in or out"}},
    {"2/4", {"Topic: Up, Down, OK", "Page: Left or Right", "Back: up one level"}},
    {"3/4", {"On a topic page, OK", "opens its app", "Flipper UI: English"}},
    {"4/4", {"Phone app: Chinese", "Added features kept", "Device test pending"}},
};

static const LabPage lab_pages_bluetooth[] = {
    {"1/7", {"Phone app connects", "over Bluetooth for", "files and status"}},
    {"2/7", {"1. Bluetooth on", "Settings: Bluetooth", "Set Bluetooth to ON"}},
    {"3/7", {"2. Phone permission", "iPhone Bluetooth on", "Allow app to use it"}},
    {"4/7", {"3. Pair on phone", "6 digits on Flipper", "Enter or confirm"}},
    {"5/7", {"4. Open the app", "Open companion app", "Choose this Flipper"}},
    {"6/7", {"No link\? Pair again", "Flipper: unpair all", "iPhone: forget it"}},
    {"7/7", {"Just a data channel", "What works depends", "on app and firmware"}},
};

static const LabPage lab_pages_infrared[] = {
    {"1/7", {"Learn remote keys", "Save, send anytime", "One remote for all"}},
    {"2/7", {"Step 1: Learn", "Learn New Remote", "Aim remote at top"}},
    {"3/7", {"Press a remote key", "Then name and save", "Repeat for each key"}},
    {"4/7", {"Step 2: Use", "Open Saved Remotes", "Pick a key to send"}},
    {"5/7", {"Universal Remotes:", "pick a device type", "Tries codes in turn"}},
    {"6/7", {"Flipper: TX and RX", "Phone: file import,", "pulse stats, labels"}},
    {"7/7", {"Only for IR devices", "Not Bluetooth or RF", "Unknown: saved RAW"}},
};

static const LabPage lab_pages_subghz[] = {
    {"1/7", {"Send and receive", "sub-1 GHz remotes:", "doorbells, outlets"}},
    {"2/7", {"Default bands:", "300-348 387-464", "779-928 MHz"}},
    {"3/7", {"Read: decode signal", "Read RAW: waveform", "Saved: view records"}},
    {"4/7", {"Frequency Analyzer:", "find the frequency,", "then use Read"}},
    {"5/7", {"Flipper: TX and RX", "Phone: file import,", "timing stats, diffs"}},
    {"6/7", {"Rolling: no replay", "Cannot decrypt data", "Own devices only"}},
    {"7/7", {"TX is limited by", "local law and bands", "Check the law first"}},
};

static const LabPage lab_pages_nfc[] = {
    {"1/6", {"Read 13.56MHz cards", "door and bus cards", "Save, emulate some"}},
    {"2/6", {"Step 1: choose Read", "Hold card to back", "Save when prompted"}},
    {"3/6", {"Step 2: open Saved", "Pick card, Emulate", "Hold back to reader"}},
    {"4/6", {"Saved auth samples:", "phone checks keys", "offline, not live"}},
    {"5/6", {"Sectors need keys", "Bank cards: no copy", "Some: UID only"}},
    {"6/6", {"NFC and 125kHz use", "different hardware", "Know your card type"}},
};

static const LabPage lab_pages_lfrfid[] = {
    {"1/5", {"Read, save LF cards", "like EM4100 and HID", "Emulate or write"}},
    {"2/5", {"Step 1: choose Read", "Hold card to back", "Wait for card ID"}},
    {"3/5", {"Step 2: open Saved", "Emulate: mimic card", "Write: onto a blank"}},
    {"4/5", {"125kHz LF only", "Encrypted: no copy", "Blanks: e.g. T5577"}},
    {"5/5", {"Flipper: read-write", "Phone: file import,", "labels, comparison"}},
};

static const LabPage lab_pages_ibutton[] = {
    {"1/5", {"Read, save contact", "keys like DS1990", "Emulate or write"}},
    {"2/5", {"Step 1: choose Read", "Touch key to back", "iButton contacts"}},
    {"3/5", {"Step 2: open Saved", "Emulate: mimic key", "Write ID: to blanks"}},
    {"4/5", {"Make good contact", "Supports Dallas etc", "Use matching blanks"}},
    {"5/5", {"Flipper: read-write", "Phone: file import,", "labels, comparison"}},
};

static const LabPage lab_pages_gpio[] = {
    {"1/6", {"USB-UART Bridge:", "PC uses Flipper to", "reach a board UART"}},
    {"2/6", {"Default pins 13, 14", "13 is TX, 14 is RX", "Cross TX and RX"}},
    {"3/6", {"Connect GND to GND", "Use 3.3V logic", "5V: level shifter"}},
    {"4/6", {"Run USB-UART Bridge", "Baud same as board", "PC: serial terminal"}},
    {"5/6", {"Lab Bridge: live", "board data to phone", "Check port and baud"}},
    {"6/6", {"AIO Board 1.4:", "chip, firmware and", "link are unverified"}},
};

static const LabPage lab_pages_files[] = {
    {"1/4", {"Records save to SD", "One folder per app", "like infrared, nfc"}},
    {"2/4", {"Desktop: press Down", "to open the Archive", "unless remapped"}},
    {"3/4", {"Copy files by PC:", "qFlipper, SD reader", "or by the phone app"}},
    {"4/4", {"BT: big files slow", "Short file names", "Back up, then edit"}},
};

static const LabPage lab_pages_phone[] = {
    {"1/5", {"Phone: heavy math", "Flipper: hardware", "and live TX and RX"}},
    {"2/5", {"App code available", "Install needs a Mac", "Bluetooth: untested"}},
    {"3/5", {"Files, record stats", "Classic keys, UART", "GPS+proxy: app open"}},
    {"4/5", {"No wider RF bands", "or longer TX range", "May not ID unknowns"}},
    {"5/5", {"If Bluetooth drops,", "Flipper works alone", "Press Back to stop"}},
};

static const LabTopic lab_topics[LAB_TOPIC_COUNT] = {
    {
        .label = "How to Use",
        .indicator = "1/10",
        .title = "How to Use",
        .footer = "L/R page, Back list",
        .launch = NULL,
        .pages = lab_pages_about,
        .page_count = 4,
    },
    {
        .label = "Bluetooth Link",
        .indicator = "2/10",
        .title = "Bluetooth Link",
        .footer = "L/R page, OK app",
        .launch = "Bluetooth",
        .pages = lab_pages_bluetooth,
        .page_count = 7,
    },
    {
        .label = "Infrared Remote",
        .indicator = "3/10",
        .title = "Infrared Remote",
        .footer = "L/R page, OK app",
        .launch = "Infrared",
        .pages = lab_pages_infrared,
        .page_count = 7,
    },
    {
        .label = "Sub-GHz Radio",
        .indicator = "4/10",
        .title = "Sub-GHz Radio",
        .footer = "L/R page, OK app",
        .launch = "Sub-GHz",
        .pages = lab_pages_subghz,
        .page_count = 7,
    },
    {
        .label = "NFC Cards",
        .indicator = "5/10",
        .title = "NFC Cards",
        .footer = "L/R page, OK app",
        .launch = "NFC",
        .pages = lab_pages_nfc,
        .page_count = 6,
    },
    {
        .label = "125kHz RFID",
        .indicator = "6/10",
        .title = "125kHz RFID",
        .footer = "L/R page, OK app",
        .launch = "125 kHz RFID",
        .pages = lab_pages_lfrfid,
        .page_count = 5,
    },
    {
        .label = "iButton Keys",
        .indicator = "7/10",
        .title = "iButton Keys",
        .footer = "L/R page, OK app",
        .launch = "iButton",
        .pages = lab_pages_ibutton,
        .page_count = 5,
    },
    {
        .label = "GPIO Serial",
        .indicator = "8/10",
        .title = "GPIO Serial",
        .footer = "L/R page, OK app",
        .launch = "GPIO",
        .pages = lab_pages_gpio,
        .page_count = 6,
    },
    {
        .label = "File Management",
        .indicator = "9/10",
        .title = "File Management",
        .footer = "L/R page, Back list",
        .launch = NULL,
        .pages = lab_pages_files,
        .page_count = 4,
    },
    {
        .label = "Phone Companion",
        .indicator = "10/10",
        .title = "Phone Companion",
        .footer = "L/R page, Back list",
        .launch = NULL,
        .pages = lab_pages_phone,
        .page_count = 5,
    },
};
