/* Generated by scripts/generate_lab_font.py. Do not edit.
 * Source: applications/main/lab/lab_content.json
 * Every string was measured against lab_font.h for its screen area.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

#define LAB_TEXT_X          2
#define LAB_TEXT_MAX_W      120
#define LAB_LIST_W          124
#define LAB_INDICATOR_RIGHT 126
#define LAB_INDICATOR_GAP   4
#define LAB_TITLE_Y         11
#define LAB_RULE_TOP        13
#define LAB_ROWS_TOP        14
#define LAB_ROW_H           12
#define LAB_ROW_BASELINE    10
#define LAB_ROWS            3
#define LAB_RULE_BOTTOM     50
#define LAB_FOOTER_Y        62
#define LAB_TEXT_MAX_BYTES  30
#define LAB_TOPIC_COUNT     10

typedef struct {
    const char* indicator;
    const char* lines[LAB_ROWS];
} LabPage;

typedef struct {
    const char* label;
    const char* indicator;
    const char* title;
    const char* footer;
    const char* launch; /* loader app name, or NULL */
    const LabPage* pages;
    uint8_t page_count;
} LabTopic;

static const char lab_menu_title[] = "中文功能指南";
static const char lab_menu_footer[] = "↑↓选择 OK查看";

static const LabPage lab_pages_about[] = {
    {"1/4", {"这里是中文说明台", "介绍各功能怎么用", "本页不收发任何信号"}},
    {"2/4", {"↑↓选择主题", "OK查看 ←→翻页", "返回键回到上一级"}},
    {"3/4", {"详情页按OK", "可打开对应原应用", "原应用界面仍是英文"}},
    {"4/4", {"本工具只做说明", "没有汉化或重写", "原有的功能应用"}},
};

static const LabPage lab_pages_bluetooth[] = {
    {"1/7", {"蓝牙让手机App", "连上Flipper", "传文件和看状态"}},
    {"2/7", {"清单1 打开蓝牙", "进Settings", "Bluetooth选ON"}},
    {"3/7", {"清单2 手机授权", "iPhone蓝牙已打开", "允许App使用蓝牙"}},
    {"4/7", {"清单3 在手机配对", "Flipper显示6位码", "照提示输入或确认"}},
    {"5/7", {"清单4 打开App", "打开配套手机App", "在App里选这台设备"}},
    {"6/7", {"还连不上就重配", "Flipper：Unpair All", "iPhone：忽略此设备"}},
    {"7/7", {"蓝牙连上只是通道", "能用哪些功能", "取决于App和固件"}},
};

static const LabPage lab_pages_infrared[] = {
    {"1/7", {"学习家电遥控按键", "保存后可随时发射", "像一个万能遥控器"}},
    {"2/7", {"步骤1 学习", "Learn New Remote", "遥控对准顶部窗口"}},
    {"3/7", {"按一下遥控按键", "成功后起名保存", "其他按键逐个学"}},
    {"4/7", {"步骤2 使用", "Saved Remotes", "选按键即可发射"}},
    {"5/7", {"万能遥控", "Universal Remotes", "会依次尝试多种码"}},
    {"6/7", {"收发由Flipper完成", "手机App规划做", "脉冲统计和整理"}},
    {"7/7", {"只对红外设备有效", "蓝牙或射频遥控不行", "未知协议存为RAW"}},
};

static const LabPage lab_pages_subghz[] = {
    {"1/7", {"收发1GHz以下的", "无线遥控信号", "如门铃和遥控插座"}},
    {"2/7", {"默认可用频段：", "300-348 387-464", "779-928 MHz"}},
    {"3/7", {"Read 解码常见协议", "Read RAW 录波形", "Saved 看已存记录"}},
    {"4/7", {"Frequency Analyzer", "先找出信号频率", "再用Read接收"}},
    {"5/7", {"收发由Flipper完成", "手机App规划做", "时序统计和比较"}},
    {"6/7", {"滚动码通常无法重放", "加密内容无法解读", "仅用于自有设备"}},
    {"7/7", {"发射受地区法规", "和频段限制", "使用前先确认合法"}},
};

static const LabPage lab_pages_nfc[] = {
    {"1/6", {"读取13.56MHz卡片", "如门禁卡和公交卡", "可保存并模拟部分卡"}},
    {"2/6", {"步骤1 选Read", "卡片贴在背面", "读完点More再Save"}},
    {"3/6", {"步骤2 选Saved", "选中卡后Emulate", "读卡器靠近背面"}},
    {"4/6", {"读卡由Flipper完成", "手机App规划做", "字段解释和比较"}},
    {"5/6", {"加密扇区需要密钥", "银行卡不能复制", "部分卡只能模拟UID"}},
    {"6/6", {"NFC和125kHz", "是两种不同硬件", "卡片类型要分清"}},
};

static const LabPage lab_pages_lfrfid[] = {
    {"1/5", {"读取低频ID卡", "如EM4100和HID", "可保存模拟或写入"}},
    {"2/5", {"步骤1 选Read", "卡片贴在背面", "等几秒显示卡号"}},
    {"3/5", {"步骤2 选Saved", "Emulate模拟卡片", "Write写入空白卡"}},
    {"4/5", {"只支持125kHz低频", "加密卡不能复制", "需T5577等空白卡"}},
    {"5/5", {"读写由Flipper完成", "手机App规划做", "记录整理和比较"}},
};

static const LabPage lab_pages_ibutton[] = {
    {"1/5", {"读取接触式钥匙扣", "如DS1990门禁钥匙", "可保存模拟或写入"}},
    {"2/5", {"步骤1 选Read", "钥匙扣贴住背面", "的iButton触点"}},
    {"3/5", {"步骤2 选Saved", "Emulate模拟钥匙", "Write ID写入空白件"}},
    {"4/5", {"触点要接触良好", "支持Dallas等协议", "写入需兼容空白件"}},
    {"5/5", {"读写由Flipper完成", "手机App规划做", "记录整理和比较"}},
};

static const LabPage lab_pages_gpio[] = {
    {"1/6", {"USB-UART Bridge", "让电脑经Flipper", "连接板子的串口"}},
    {"2/6", {"接线 默认13和14脚", "13为TX 14为RX", "TX与RX交叉相接"}},
    {"3/6", {"GND与GND相连", "按3.3V电平使用", "5V设备要电平转换"}},
    {"4/6", {"步骤 进入Bridge", "波特率与板子一致", "电脑用串口软件看"}},
    {"5/6", {"USB串口不经手机", "手机日志助手规划中", "高速数据经蓝牙可能丢"}},
    {"6/6", {"AIO Board 1.4", "芯片固件待核实", "本机连接未验证"}},
};

static const LabPage lab_pages_files[] = {
    {"1/4", {"记录存在SD卡", "各功能分目录", "如infrared nfc"}},
    {"2/4", {"桌面短按下键", "打开Archive浏览", "按键设置改过则不同"}},
    {"3/4", {"电脑可用qFlipper", "或拔卡用读卡器", "手机App也可传文件"}},
    {"4/4", {"蓝牙传大文件较慢", "文件名建议用英文", "改动前请先备份"}},
};

static const LabPage lab_pages_phone[] = {
    {"1/5", {"手机负责重计算", "Flipper负责硬件", "和实时收发"}},
    {"2/5", {"配套App仍在开发", "下列为规划功能", "以实际版本为准"}},
    {"3/5", {"规划：红外脉冲统计", "记录比较与搜索", "已知协议候选匹配"}},
    {"4/5", {"不能扩大射频频段", "也不增加发射距离", "未知信号未必能识别"}},
    {"5/5", {"蓝牙断开后", "Flipper仍可单独用", "本机按返回可停止"}},
};

static const LabTopic lab_topics[LAB_TOPIC_COUNT] = {
    {
        .label = "使用说明",
        .indicator = "1/10",
        .title = "使用说明",
        .footer = "←→翻页 返回列表",
        .launch = NULL,
        .pages = lab_pages_about,
        .page_count = 4,
    },
    {
        .label = "蓝牙连接",
        .indicator = "2/10",
        .title = "蓝牙连接",
        .footer = "←→翻页 OK打开应用",
        .launch = "Bluetooth",
        .pages = lab_pages_bluetooth,
        .page_count = 7,
    },
    {
        .label = "红外遥控",
        .indicator = "3/10",
        .title = "红外遥控",
        .footer = "←→翻页 OK打开应用",
        .launch = "Infrared",
        .pages = lab_pages_infrared,
        .page_count = 7,
    },
    {
        .label = "Sub-GHz无线",
        .indicator = "4/10",
        .title = "Sub-GHz无线",
        .footer = "←→翻页 OK打开应用",
        .launch = "Sub-GHz",
        .pages = lab_pages_subghz,
        .page_count = 7,
    },
    {
        .label = "NFC卡片",
        .indicator = "5/10",
        .title = "NFC卡片",
        .footer = "←→翻页 OK打开应用",
        .launch = "NFC",
        .pages = lab_pages_nfc,
        .page_count = 6,
    },
    {
        .label = "125kHz RFID",
        .indicator = "6/10",
        .title = "125kHz RFID",
        .footer = "←→翻页 OK打开应用",
        .launch = "125 kHz RFID",
        .pages = lab_pages_lfrfid,
        .page_count = 5,
    },
    {
        .label = "iButton钥匙",
        .indicator = "7/10",
        .title = "iButton钥匙",
        .footer = "←→翻页 OK打开应用",
        .launch = "iButton",
        .pages = lab_pages_ibutton,
        .page_count = 5,
    },
    {
        .label = "GPIO串口",
        .indicator = "8/10",
        .title = "GPIO串口",
        .footer = "←→翻页 OK打开应用",
        .launch = "GPIO",
        .pages = lab_pages_gpio,
        .page_count = 6,
    },
    {
        .label = "文件管理",
        .indicator = "9/10",
        .title = "文件管理",
        .footer = "←→翻页 返回列表",
        .launch = NULL,
        .pages = lab_pages_files,
        .page_count = 4,
    },
    {
        .label = "手机算力",
        .indicator = "10/10",
        .title = "手机算力",
        .footer = "←→翻页 返回列表",
        .launch = NULL,
        .pages = lab_pages_phone,
        .page_count = 5,
    },
};
